'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Friend NotInheritable Class AppInit
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As AppInit = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New AppInit()),AppInit)
    
    Public Shared ReadOnly Property [Default]() As AppInit
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DbServer() As String
        Get
            Return CType(Me("DbServer"),String)
        End Get
        Set
            Me("DbServer") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DbUsername() As String
        Get
            Return CType(Me("DbUsername"),String)
        End Get
        Set
            Me("DbUsername") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DbPassword() As String
        Get
            Return CType(Me("DbPassword"),String)
        End Get
        Set
            Me("DbPassword") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property DbDatabase() As String
        Get
            Return CType(Me("DbDatabase"),String)
        End Get
        Set
            Me("DbDatabase") = value
        End Set
    End Property
End Class
